// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pool;

namespace Pool.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Pool.Models.Bowl", b =>
                {
                    b.Property<int>("BowlId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("WorkLoad");

                    b.HasKey("BowlId");

                    b.ToTable("Bowls");
                });

            modelBuilder.Entity("Pool.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd();

                    b.Property<byte>("Age");

                    b.Property<string>("FName");

                    b.Property<string>("LName");

                    b.Property<byte>("MedicalExamination");

                    b.Property<string>("NumberPhone");

                    b.Property<string>("Payment");

                    b.Property<int?>("ServiceId");

                    b.Property<int?>("SubscriptionId");

                    b.HasKey("ClientId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Pool.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ServiceName");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Pool.Models.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd();

                    b.Property<byte>("QuantityOfOccupation");

                    b.Property<string>("Time");

                    b.HasKey("SubscriptionId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Pool.Models.Client", b =>
                {
                    b.HasOne("Pool.Models.Service", "Service")
                        .WithMany("Client")
                        .HasForeignKey("ServiceId");

                    b.HasOne("Pool.Models.Subscription", "Subscription")
                        .WithMany("Client")
                        .HasForeignKey("SubscriptionId");
                });
#pragma warning restore 612, 618
        }
    }
}
